# Generated by Django 3.0.2 on 2020-07-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='context',
            new_name='content',
        ),
    ]
