# Generated by Django 3.0.2 on 2020-08-10 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_blogpost_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='user_id',
            new_name='user',
        ),
    ]
