# Generated by Django 3.0.2 on 2020-08-29 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20200828_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updated', '-time_stamp']},
        ),
    ]
